<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EC2AMAZ-S11DBRH" failures="1" tests="2" name="Default test" time="5.856" errors="0" timestamp="2023-12-19T06:40:20 GMT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.747"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.164">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at stepDefs.OrderStepDef.should_navigate_to_checkout_page(OrderStepDef.java:68)
at âœ½.Should navigate to Checkout page(file:///C:/SeleniumProject/BDDPOMDemo/src/test/resources/features/PlaceOrder.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
